# Generated by Django 5.1.1 on 2024-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisteredBooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredbooks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='registeredbooks',
            name='title',
        ),
        migrations.RemoveField(
            model_name='registeredbooks',
            name='year_published',
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='book_type',
            field=models.CharField(blank=True, choices=[('E-book', 'E-book'), ('Physical', 'Physical')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='books_condition',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='books_name',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='language',
            field=models.CharField(default='čeština', max_length=50),
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='number_of_pages',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='reading_progress',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Unread', 'Unread'), ('In progress', 'In progress')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registeredbooks',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
